
# plans = Plan.create([{ name: 'SIN PLAN' },  { name:"Platinum medium"}, { name:"Platinum 20 basico"}, { name:"Star 20 medium"},{ name: "Star 20 pro"}, { name:"Platinum 20 pro"}, { name:"Gold 40 pro A"},{ name: "Platinum 20 Pro"}, { name:"Star 20 Pro"}, { name:"Star 20 basico"}])


Owner.create(id_propietario: 1 , email:  'contacto@almabella.cl' )
Owner.create(id_propietario: 2 , email:  'contacto@auraypiel.cl' )
Owner.create(id_propietario: 3 , email:  'contacto@beautychic.cl' )
Owner.create(id_propietario: 4 , email:  'contacto@esteticabeautycorp.cl' )
Owner.create(id_propietario: 5 , email:  'contacto@bebeauty.cl' )
Owner.create(id_propietario: 6 , email:  'contacto@beform.cl' )
Owner.create(id_propietario: 7 , email:  'contacto@bellisimalascondes.cl' )
Owner.create(id_propietario: 9 , email:  'contacto@clinicabeautycare.cl' )
Owner.create(id_propietario: 10, email:  'contacto@clinicabenatural.cl' )
Owner.create(id_propietario: 11, email:  'contacto@clinicaforeverbeauty.cl' )
Owner.create(id_propietario: 12, email:  'contacto@clinicalafemme.cl' )
Owner.create(id_propietario: 13, email:  'contacto@clinicalaserbelle.cl' )
Owner.create(id_propietario: 14, email:  'contacto@clinicalebon.cl' )
Owner.create(id_propietario: 15, email:  'contacto@clinicavitacare.cl' )
Owner.create(id_propietario: 16, email:  'contacto@contornocorpo.cl' )
Owner.create(id_propietario: 17, email:  'contacto@clinicadiana.cl' )
Owner.create(id_propietario: 18, email:  'contacto@divaesthetic.cl' )
Owner.create(id_propietario: 20, email:  'contacto@esteticabadajoz.cl' )
Owner.create(id_propietario: 21, email:  'contacto@esteticabeautycorp.cl' )
Owner.create(id_propietario: 22, email:  'contacto@esteticaelgolf.cl' )
Owner.create(id_propietario: 23, email:  'contacto@esteticaelgolf.cl' )
Owner.create(id_propietario: 24, email:  'contacto@esteticalcantara.cl' )
Owner.create(id_propietario: 25, email:  'contacto@esteticanaturalskin.cl' )
Owner.create(id_propietario: 26, email:  'contacto@esteticasantiagobueras.cl' )
Owner.create(id_propietario: 27, email:  'contacto@esteticatobalaba.cl' )
Owner.create(id_propietario: 28, email:  'contacto@esteticabeautyart.cl' )
Owner.create(id_propietario: 29, email:  'contacto@fastbeauty.cl' )
Owner.create(id_propietario: 30, email:  'contacto@fisiospa.cl' )
Owner.create(id_propietario: 32, email:  'contacto@contornocorpo.cl' )
Owner.create(id_propietario: 33, email:  'contacto@kinedos.cl' )
Owner.create(id_propietario: 34, email:  'contacto@kineline.cl' )
Owner.create(id_propietario: 35, email:  'contacto@kinest.cl' )
Owner.create(id_propietario: 36, email:  'contacto@maislinda.cl' )
Owner.create(id_propietario: 37, email:  'contacto@makiss.cl' )
Owner.create(id_propietario: 38, email:  'contacto@makiss.cl' )
Owner.create(id_propietario: 40, email:  'contacto@morabeauty.cl' )
Owner.create(id_propietario: 41, email:  'contacto@clinicanaturalessense.cl' )
Owner.create(id_propietario: 42, email:  'contacto@naturalkine.cl' )
Owner.create(id_propietario: 43, email:  'contacto@naturalsthetic.cl' )
Owner.create(id_propietario: 44, email:  'contacto@newlifekine.cl' )
Owner.create(id_propietario: 45, email:  'contacto@saludesvida.cl' )
Owner.create(id_propietario: 46, email:  'contacto@siluetestetic.cl' )
Owner.create(id_propietario: 47, email:  'contacto@venusspa.cl' )
Owner.create(id_propietario: 48, email:  'contacto@vitaline.cl' )
Owner.create(id_propietario: 49, email:  'contacto@esteticalisse.cl' )
Owner.create(id_propietario: 50, email:  'contacto@alwaysbeauty.cl' )
Owner.create(id_propietario: 51, email:  'contacto@beline.cl' )
Owner.create(id_propietario: 52, email:  'contacto@ceklife.cl' )
Owner.create(id_propietario: 53, email:  'contacto@clinicathompson.cl' )
Owner.create(id_propietario: 54, email:  'contacto@dermaluz.cl' )
Owner.create(id_propietario: 55, email:  'contacto@clinicanapoli.cl')