
# plans = Plan.create([{ name: 'SIN PLAN' },  { name:"Platinum medium"}, { name:"Platinum 20 basico"}, { name:"Star 20 medium"},{ name: "Star 20 pro"}, { name:"Platinum 20 pro"}, { name:"Gold 40 pro A"},{ name: "Platinum 20 Pro"}, { name:"Star 20 Pro"}, { name:"Star 20 basico"}])


# Owner.create(id_propietario: 1 , email:  'contacto@almabella.cl' )
# Owner.create(id_propietario: 2 , email:  'contacto@auraypiel.cl' )
# Owner.create(id_propietario: 3 , email:  'contacto@beautychic.cl' )
# Owner.create(id_propietario: 4 , email:  'contacto@esteticabeautycorp.cl' )
# Owner.create(id_propietario: 5 , email:  'contacto@bebeauty.cl' )
# Owner.create(id_propietario: 6 , email:  'contacto@beform.cl' )
# Owner.create(id_propietario: 7 , email:  'contacto@bellisimalascondes.cl' )
# Owner.create(id_propietario: 9 , email:  'contacto@clinicabeautycare.cl' )
# Owner.create(id_propietario: 10, email:  'contacto@clinicabenatural.cl' )
# Owner.create(id_propietario: 11, email:  'contacto@clinicaforeverbeauty.cl' )
# Owner.create(id_propietario: 12, email:  'contacto@clinicalafemme.cl' )
# Owner.create(id_propietario: 13, email:  'contacto@clinicalaserbelle.cl' )
# Owner.create(id_propietario: 14, email:  'contacto@clinicalebon.cl' )
# Owner.create(id_propietario: 15, email:  'contacto@clinicavitacare.cl' )
# Owner.create(id_propietario: 16, email:  'contacto@contornocorpo.cl' )
# Owner.create(id_propietario: 17, email:  'contacto@clinicadiana.cl' )
# Owner.create(id_propietario: 18, email:  'contacto@divaesthetic.cl' )
# Owner.create(id_propietario: 20, email:  'contacto@esteticabadajoz.cl' )
# Owner.create(id_propietario: 21, email:  'contacto@esteticabeautycorp.cl' )
# Owner.create(id_propietario: 22, email:  'contacto@esteticaelgolf.cl' )
# Owner.create(id_propietario: 23, email:  'contacto@esteticaelgolf.cl' )
# Owner.create(id_propietario: 24, email:  'contacto@esteticalcantara.cl' )
# Owner.create(id_propietario: 25, email:  'contacto@esteticanaturalskin.cl' )
# Owner.create(id_propietario: 26, email:  'contacto@esteticasantiagobueras.cl' )
# Owner.create(id_propietario: 27, email:  'contacto@esteticatobalaba.cl' )
# Owner.create(id_propietario: 28, email:  'contacto@esteticabeautyart.cl' )
# Owner.create(id_propietario: 29, email:  'contacto@fastbeauty.cl' )
# Owner.create(id_propietario: 30, email:  'contacto@fisiospa.cl' )
# Owner.create(id_propietario: 32, email:  'contacto@contornocorpo.cl' )
# Owner.create(id_propietario: 33, email:  'contacto@kinedos.cl' )
# Owner.create(id_propietario: 34, email:  'contacto@kineline.cl' )
# Owner.create(id_propietario: 35, email:  'contacto@kinest.cl' )
# Owner.create(id_propietario: 36, email:  'contacto@maislinda.cl' )
# Owner.create(id_propietario: 37, email:  'contacto@makiss.cl' )
# Owner.create(id_propietario: 38, email:  'contacto@makiss.cl' )
# Owner.create(id_propietario: 40, email:  'contacto@morabeauty.cl' )
# Owner.create(id_propietario: 41, email:  'contacto@clinicanaturalessense.cl' )
# Owner.create(id_propietario: 42, email:  'contacto@naturalkine.cl' )
# Owner.create(id_propietario: 43, email:  'contacto@naturalsthetic.cl' )
# Owner.create(id_propietario: 44, email:  'contacto@newlifekine.cl' )
# Owner.create(id_propietario: 45, email:  'contacto@saludesvida.cl' )
# Owner.create(id_propietario: 46, email:  'contacto@siluetestetic.cl' )
# Owner.create(id_propietario: 47, email:  'contacto@venusspa.cl' )
# Owner.create(id_propietario: 48, email:  'contacto@vitaline.cl' )
# Owner.create(id_propietario: 49, email:  'contacto@esteticalisse.cl' )
# Owner.create(id_propietario: 50, email:  'contacto@alwaysbeauty.cl' )
# Owner.create(id_propietario: 51, email:  'contacto@beline.cl' )
# Owner.create(id_propietario: 52, email:  'contacto@ceklife.cl' )
# Owner.create(id_propietario: 53, email:  'contacto@clinicathompson.cl' )
# Owner.create(id_propietario: 54, email:  'contacto@dermaluz.cl' )
# Owner.create(id_propietario: 55, email:  'contacto@clinicanapoli.cl')



Kinesiologist.create(id_centro:1, nombre: 'Ma. Begoña')
Kinesiologist.create(id_centro:1, nombre: 'kines')
Kinesiologist.create(id_centro:1, nombre: 'Cecilia Orellana ')
Kinesiologist.create(id_centro:1, nombre: 'barbara santibañez')
Kinesiologist.create(id_centro:1, nombre: 'Yudelyn Rios')
Kinesiologist.create(id_centro:1, nombre: 'Mourine')
Kinesiologist.create(id_centro:1, nombre: 'CAMILA MONTES')
Kinesiologist.create(id_centro:2, nombre: 'kines')
Kinesiologist.create(id_centro:2, nombre: 'Sara Carrasco')
Kinesiologist.create(id_centro:3, nombre: 'kines')
Kinesiologist.create(id_centro:3, nombre: 'Elizabeth Galdames')
Kinesiologist.create(id_centro:3, nombre: 'Carolina Gonzalez')
Kinesiologist.create(id_centro:3, nombre: 'Valentina ')
Kinesiologist.create(id_centro:3, nombre: 'Milena Altamirano')
Kinesiologist.create(id_centro:4, nombre: 'yubitsa')
Kinesiologist.create(id_centro:4, nombre: 'Teresita Osorio')
Kinesiologist.create(id_centro:4, nombre: 'kines')
Kinesiologist.create(id_centro:4, nombre: 'valeria')
Kinesiologist.create(id_centro:5, nombre: 'Estefania Muller')
Kinesiologist.create(id_centro:5, nombre: 'kines')
Kinesiologist.create(id_centro:5, nombre: 'Valentina Maulen')
Kinesiologist.create(id_centro:5, nombre: 'Barbara Painequir')
Kinesiologist.create(id_centro:5, nombre: 'Carolina Palacios')
Kinesiologist.create(id_centro:5, nombre: 'Paula')
Kinesiologist.create(id_centro:5, nombre: 'Pamela Lagos')
Kinesiologist.create(id_centro:5, nombre: 'Carolina Rivero')
Kinesiologist.create(id_centro:5, nombre: 'Melissa')
Kinesiologist.create(id_centro:5, nombre: 'Paloma')
Kinesiologist.create(id_centro:5, nombre: 'Sandy')
Kinesiologist.create(id_centro:6, nombre: 'kines')
Kinesiologist.create(id_centro:6, nombre: 'Daniela Gutierrez')
Kinesiologist.create(id_centro:6, nombre: 'Jenny')
Kinesiologist.create(id_centro:6, nombre: 'Emily Gajardo')
Kinesiologist.create(id_centro:6, nombre: 'Teresita')
Kinesiologist.create(id_centro:6, nombre: 'Carolina Gantiva')
Kinesiologist.create(id_centro:6, nombre: 'Gladis')
Kinesiologist.create(id_centro:6, nombre: 'Karla')
Kinesiologist.create(id_centro:6, nombre: 'Macarena')
Kinesiologist.create(id_centro:6, nombre: 'victoria')
Kinesiologist.create(id_centro:6, nombre: 'Camila')
Kinesiologist.create(id_centro:6, nombre: 'Paula Vidal')
Kinesiologist.create(id_centro:7, nombre: 'yenifer')
Kinesiologist.create(id_centro:7, nombre: 'Nicole Vargas')
Kinesiologist.create(id_centro:7, nombre: 'Karla Alvarez Donoso')
Kinesiologist.create(id_centro:9, nombre: 'dps')
Kinesiologist.create(id_centro:9, nombre: 'Valeska Córdova ')
Kinesiologist.create(id_centro:9, nombre: 'CAMILA')
Kinesiologist.create(id_centro:9, nombre: 'Nicole Calderon')
Kinesiologist.create(id_centro:9, nombre: 'Sandy Millan')
Kinesiologist.create(id_centro:9, nombre: 'kines')
Kinesiologist.create(id_centro:10, nombre: 'Maria Paz')
Kinesiologist.create(id_centro:10, nombre: 'Tammy')
Kinesiologist.create(id_centro:10, nombre: 'Natalia')
Kinesiologist.create(id_centro:10, nombre: 'Paula Valenzuela')
Kinesiologist.create(id_centro:10, nombre: 'Nicolets')
Kinesiologist.create(id_centro:10, nombre: 'kines')
Kinesiologist.create(id_centro:11, nombre: 'Jenny Bouffanais')
Kinesiologist.create(id_centro:11, nombre: 'kines')
Kinesiologist.create(id_centro:11, nombre: 'Claudia Escarate')
Kinesiologist.create(id_centro:11, nombre: 'Paola Vega')
Kinesiologist.create(id_centro:11, nombre: 'Catalina Albuerno')
Kinesiologist.create(id_centro:12, nombre: 'Lilian')
Kinesiologist.create(id_centro:12, nombre: 'natalia')
Kinesiologist.create(id_centro:12, nombre: 'kines')
Kinesiologist.create(id_centro:12, nombre: 'josefa')
Kinesiologist.create(id_centro:12, nombre: 'Romina')
Kinesiologist.create(id_centro:12, nombre: 'valentina')
Kinesiologist.create(id_centro:12, nombre: 'javiera')
Kinesiologist.create(id_centro:13, nombre: 'Scarlet Matus')
Kinesiologist.create(id_centro:13, nombre: 'MELANIE LOPEZ')
Kinesiologist.create(id_centro:13, nombre: 'Tabatha Mangelsdorff')
Kinesiologist.create(id_centro:13, nombre: 'MACARENA')
Kinesiologist.create(id_centro:13, nombre: 'marylin ')
Kinesiologist.create(id_centro:13, nombre: 'kines')
Kinesiologist.create(id_centro:13, nombre: 'vanessa gaete')
Kinesiologist.create(id_centro:14, nombre: 'Jennifer Bouffanais')
Kinesiologist.create(id_centro:14, nombre: 'kines')
Kinesiologist.create(id_centro:14, nombre: 'Natalia Montenegro')
Kinesiologist.create(id_centro:14, nombre: 'Claudia Escarate')
Kinesiologist.create(id_centro:15, nombre: 'kines')
Kinesiologist.create(id_centro:15, nombre: 'Tania Manquez')
Kinesiologist.create(id_centro:16, nombre: 'Camila')
Kinesiologist.create(id_centro:16, nombre: 'Claudia')
Kinesiologist.create(id_centro:16, nombre: 'Carolina')
Kinesiologist.create(id_centro:16, nombre: 'kines')
Kinesiologist.create(id_centro:17, nombre: 'Francisca Jara')
Kinesiologist.create(id_centro:17, nombre: 'kines')
Kinesiologist.create(id_centro:17, nombre: 'katherine')
Kinesiologist.create(id_centro:17, nombre: 'Yesenia vargas ')
Kinesiologist.create(id_centro:18, nombre: 'Denisse')
Kinesiologist.create(id_centro:18, nombre: 'Daniela Contreras')
Kinesiologist.create(id_centro:18, nombre: 'Elizabeth')
Kinesiologist.create(id_centro:18, nombre: 'kines')
Kinesiologist.create(id_centro:18, nombre: 'Joice')
Kinesiologist.create(id_centro:18, nombre: 'Daniela')
Kinesiologist.create(id_centro:18, nombre: 'Ninoska Martinez')
Kinesiologist.create(id_centro:18, nombre: 'Diva')
Kinesiologist.create(id_centro:18, nombre: 'Yessenia')
Kinesiologist.create(id_centro:18, nombre: 'Camila')
Kinesiologist.create(id_centro:18, nombre: 'Tamara')
Kinesiologist.create(id_centro:18, nombre: 'Yessenia Vargas')
Kinesiologist.create(id_centro:18, nombre: 'Rachel Oñate')
Kinesiologist.create(id_centro:20, nombre: 'katherinne')
Kinesiologist.create(id_centro:20, nombre: 'admin')
Kinesiologist.create(id_centro:20, nombre: 'Valesca Cordova')
Kinesiologist.create(id_centro:20, nombre: 'Yicel')
Kinesiologist.create(id_centro:20, nombre: 'Constanza Araya')
Kinesiologist.create(id_centro:20, nombre: 'Yessenia')
Kinesiologist.create(id_centro:20, nombre: 'yone')
Kinesiologist.create(id_centro:20, nombre: 'jessica Orellana')
Kinesiologist.create(id_centro:20, nombre: 'kines')
Kinesiologist.create(id_centro:20, nombre: 'Daniela Alejandra Armijo Quiñones')
Kinesiologist.create(id_centro:20, nombre: 'caro')
Kinesiologist.create(id_centro:20, nombre: 'Yertty Rojas')
Kinesiologist.create(id_centro:20, nombre: 'Carolina')
Kinesiologist.create(id_centro:21, nombre: 'Pilar Zuniga')
Kinesiologist.create(id_centro:21, nombre: 'Claudia Gonzalez')
Kinesiologist.create(id_centro:21, nombre: 'Daniela ')
Kinesiologist.create(id_centro:21, nombre: 'Karina Rojas')
Kinesiologist.create(id_centro:21, nombre: 'kines')
Kinesiologist.create(id_centro:22, nombre: 'Debora Riveros')
Kinesiologist.create(id_centro:22, nombre: 'Nicole Calderon')
Kinesiologist.create(id_centro:22, nombre: 'Nicole Gonzalez')
Kinesiologist.create(id_centro:22, nombre: 'kines')
Kinesiologist.create(id_centro:22, nombre: 'Milena')
Kinesiologist.create(id_centro:23, nombre: 'kines')
Kinesiologist.create(id_centro:23, nombre: 'Carolina')
Kinesiologist.create(id_centro:23, nombre: 'Betty')
Kinesiologist.create(id_centro:23, nombre: 'Katherinne Loncomil')
Kinesiologist.create(id_centro:23, nombre: 'Carla Ordenes')
Kinesiologist.create(id_centro:24, nombre: 'Nathaly')
Kinesiologist.create(id_centro:24, nombre: 'CAMILA')
Kinesiologist.create(id_centro:24, nombre: 'CAROLINA MUÑOZ')